### ISSUE TITLE
Nextgen Gallery breaks Tailor

### ISSUE THREAD

**Issue by robertminer1** [andrew-worsfold/tailor#10]
Hi!  Love the plugin so far!  Nextgen gallery is a really popular gallery plugin, but it seems to break Tailor.  Any suggestions on how to work around this?  I'm planning on implementing this into production asap.

**Comment by andrew-worsfold** [comment]
Hi Robert - Glad you like it!  I'm not really familiar with the NextGEN gallery plugin.  After installing and activating it, I cannot get it to work with or without Tailor activated.  Could you please describe to me what appears to be breaking when Tailor is activated and what the steps to reproduce the problem are?

**Comment by robertminer1** [comment]
1.  Install Tailor & Activate Tailor
2.  Install NextGen and Activate It
3.  Try To "Tailor" a page.

Tailor just seems to be loading, not doing anything.  I noticed in the console that Jquery Migrate is called twice, which probably means that Jquery is being called twice and potentially breaking Tailor.  NextGen gallery has a lot of moving components, and I couldn't seem to find where their style or JS was being called from to unhook the action.  I suspect that is the culprit.

**Comment by andrew-worsfold** [comment]
Thanks for confirming!  I was able to reproduce and have added compatibility in the latest version of Tailor (1.3.0).  Can you please test using this latest version and let me know if it works for you?

**Comment by andrew-worsfold** [comment]
The fix implemented in version 1.3.0 has fixed this issue on every environment that I have tested on.  As I've not heard anything back, I'll close this issue but please don't hesitate to get back in touch if you have any more trouble with Tailor/NextGEN.
