### ISSUE TITLE
Is it possible to create a new section?

### ISSUE THREAD

**Issue by miltonbayermatt** [andrew-worsfold/tailor#102]
Is it possible to create a new section that would appear underneath 'Elements' and above 'Templates' which I could also add elements into? I have a large number of custom elements that I want to add and being able to section them would be very useful

Thanks

**Comment by andrew-worsfold** [comment]
@miltonbayermatt -

Yes, it's possible.  Sections within the sidebar can be extended in a similar way to elements with custom PHP and JS code.  This isn't a feature that exists "out of the box", though.

**Comment by miltonbayermatt** [comment]
Thanks Andrew, I thought that might be the case.
