### ISSUE TITLE
Different settings per device

### ISSUE THREAD

**Issue by julianxhokaxhiu** [andrew-worsfold/tailor#103]
Hi,

I saw that taylor has a device switch on the left bar, meanwhile editing the page. Would be nice if *any* widget could had a possibility to override settings depending on the target device. This is the classical case for carousels, where you want to show 5 elements on desktop, 3 on tablets and 1 on mobile.

At the moment this is not possible, or I didn't saw where to configure this. Do you have any plan for this?

Thank you in advance,
Julian

**Comment by andrew-worsfold** [comment]
@julianxhokaxhiu -

Device-specific settings are a built-in feature of Tailor, but aren't used for all options.  You can extend any element you like to include settings for mobile, tablet and desktop.   Widgets are a special type of element (given that they are a WordPress concept); they derive their core settings from the widget itself, however you can still extend them like you would any element with your own settings etc.

**Comment by julianxhokaxhiu** [comment]
Sorry, I used the wrong wording. In my case I was referring to *core* Tailor widgets. Elements, or you call them. For eg. Woocommerce Products from tailor-woocommerce package.

That one doesn't inherit specific device settings. If it's possible to extend them, how can I do it? Can you point me to a specific documentation?

Thank you in advance.
