### ISSUE TITLE
Grid: Span multiple rows/columns

### ISSUE THREAD

**Issue by strarsis** [andrew-worsfold/tailor#106]
I cannot find an option to let a single grid item span multiple rows/columns in a Tailor grid.

**Comment by andrew-worsfold** [comment]
@strarsis - The standard grid system is not built for this use case (and is shared by multiple elements), but you could easily create a custom element to allow for this and whatever else you need.

**Comment by strarsis** [comment]
@andrew-worsfold: So I can write a custom element based off the grid element 
for adding row-/col-span support to its grid elements?

**Comment by andrew-worsfold** [comment]
@strarsis -

You could just override the default grid CSS with your own if you wanted to.  To have more control over which grid items behave differently, you'd probably want a custom element (using the Grid element as a guide if you like).

**Comment by strarsis** [comment]
@andrew-worsfold: Are there some guides about how to extend an existing Tailor element? I would prefer to use the Tailor Grid as starting point.
The Tailor Grid is great, elements align vertically and it looks very nice (including support for background images). The only thing missing is "rowspan/colspan".

**Comment by andrew-worsfold** [comment]
@strarsis depending on what your goals are, you can extend an element or just create your own custom one using the parts of the other element that you like.  If you're essentially wanting the Grid element with an option for "rowspan/colspan", you're probably actually looking at a change to the Grid Item element.

This could be a simple CSS change along with either:
1) A custom classname (which you can add to any instantiated element); or
2) An extra control added to the Grid Item element (examples of this in the sample theme/extension repos).

If you go with the second option, you would also want to update the associated shortcode rendering function using the relevant filters to ensure that the necessary classname/markup is added.

Hope that helps!
Andrew

**Comment by strarsis** [comment]
@andrew-worsfold: This is a feature I can imagine is quite demanded, are there plans to add this feature officially in the near future?

**Comment by strarsis** [comment]
@andrew-worsfold: Sadly, for row spanning grid items, wrapper elements are also required.

**Comment by andrew-worsfold** [comment]
@strarsis I don't have plans to add this feature myself, however as this is an open source project if someone wants to raise a PR with this functionality I will be happy to review and commit it.
