### ISSUE TITLE
I want to put the complete posts

### ISSUE THREAD

**Issue by DanielSanchez94** [andrew-worsfold/tailor#114]
In one of my pages I need my post to show the complete entries, without having to read more.
Thank you.

**Comment by andrew-worsfold** [comment]
The posts element is not designed for this use case, however you could create a custom element or modify the output of the Posts element to achieve the desired behaviour (this would require some custom code).

**Comment by DanielSanchez94** [comment]
Hello, I would need if you can do me the favor, that you indicate to me what are the steps to make a new element.

The idea would be to make a new post-new element that has the option of showing it complete.

thank you very much.

Greetings.

**Comment by andrew-worsfold** [comment]
@DanielSanchez94 -

Please refer to the documentation on support.gettailor.com or the sample extension/theme repositories for more information on how to create custom elements.  You can also look at the Tailor code itself, as the element could look very similar to the Posts element.
