### ISSUE TITLE
WP API V2 Support

### ISSUE THREAD

**Issue by xpluscal** [andrew-worsfold/tailor#12]
It would be great to be able to get tailor data via the API in order to enable react frontends with wordpress backend etc.

**Comment by andrew-worsfold** [comment]
Great recommendation!  Do you have any examples of the sorts of things you'd ideally like to do with the API when available?  What sort of resources/endpoints do you envision?

**Comment by xpluscal** [comment]
I'm currently working on building a react/redux-wp application. So essentially wordpress ist just used as the content management system and content deliverer. So it would be nice if the components created by tailoring a post could be retrieved as a nested json-data structure so that your components could be rebuild as react components.

There is an api for ACF which offers similar functionality. So if I fetch a post or page, there could be a field in the format:

```
tailor: {
   row: {
      contents: {
         col: {
            content: "Content 1",
            attributes: {
                ...
            } 
         }
         col: {
             content: "Content 2",
             ....
         }
      }
   },
   row: {
      contents: {
          map: {
               ...
          }
       }
   }
}

```

or similar.
This would avoid having to rely on the served html but instead being view agnostic.

Best
C

**Comment by andrew-worsfold** [comment]
Are you proposing that the standard WP API post/page response be augmented to include Tailor element data, or do you think a standalone Tailor API would be preferable (e.g., 'tailor/v1/..')?

**Comment by xpluscal** [comment]
Since tailor elements are always associated with a certain post or a page, I think I'd go with the first option.
It might be an option to later implement a standaline API as well, if the need comes about.

I personally think that this plugin for adding REST API support for Advanced Custom Fields might be a good reference:
https://github.com/airesvsg/acf-to-rest-api

Btw. that's why I asked about the integration of custom post types as well, since ACF offers Custom Post Type support by default and have also integrated this into their API.

**Comment by andrew-worsfold** [comment]
That ACF API plugin is indeed a good reference.  Tailor's models are handled independently and linked by IDs, rather than a parent having nested children like in your example above.  Of course it's possible to restructure the data before returning it, so that's not necessarily a constraint.

At this stage I am thinking of having elements (i.e., all registered element types) and templates as resource types that are independent of posts.  Models (i.e., instantiated elements) and settings are resources that are specific to a page.  Do you have any other resource types in mind?

**Comment by xpluscal** [comment]
Sounds great.
Right now, I can't think of any other.
ACF also has a so called "flexible-content"-field. What it returns is similar to what I explained, only that there is no comfort such as WYSIWYG as with tailor.

Do you have any idea when you're thinking about implementing the API?

**Comment by xpluscal** [comment]
Here is the link to the flexible content fields doc:
https://www.advancedcustomfields.com/resources/flexible-content/#template-usage

**Comment by andrew-worsfold** [comment]
The latest version of Tailor on GitHub (1.4.0) includes the initial Tailor REST API.  This is a big release in terms of code changes, so I will perform some more testing before uploading this to the WordPress plugin repository.  Please check it out if you have time, as I'd love some feedback.

I'll close this issue now (as it was for the creation of the API), however please don't hesitate to raise another specific issue if you find an issue or have a feature request!
