### ISSUE TITLE
Tailor option not appearing

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [andrew-worsfold/tailor#122]
I am using 
Wordpress - 4.8.
Theme - twenty seventeen 
Plugin - only Tailor.
My site is on localhost.

After activation, I have enabled tailor for both page and post, but no where I can see the option to "Tailor This Page" as described in the [documentation](https://support.gettailor.com/hc/en-us/articles/222093467-Tailoring-a-post) . Please reply fast, is this requires something else to work ? 

Update: I can see options if I am trying in [sandbox](https://addendio.com/try-plugin/?slug=tailor).  but in sandbox, I am unable to edit the page/post !!

**Comment by andrew-worsfold** [comment]
I am unable to replicate this using the exact same setup as you.  Are you seeing any errors in the browser console?

**Comment by PrafullaKumarSahu** [comment]
On localhost, there is no error even in console, but in sandbox there is an error in console, whihc does not seems to related to tailor.

```
uncaught TypeError: Cannot read property 'findWhere' of undefined
    at n.applyDefaults (canvas.min.js:3)
    at Function.m.each.m.forEach (underscore.min.js:5)
    at n.add (canvas.min.js:3)
    at n.reset (backbone.min.js:1)
    at n.e.Collection (backbone.min.js:1)
    at new n (backbone.min.js:1)
    at n.onBeforeStart (canvas.min.js:5)
    at Object._triggerMethod (backbone.marionette.min.js:1)
    at n.f.triggerMethod (backbone.marionette.min.js:1)
    at n.start (backbone.marionette.min.js:2)

```

**Comment by PrafullaKumarSahu** [comment]
Oh! The console error in sandbox is from Tailor plugin.

**Comment by PrafullaKumarSahu** [comment]
Thank you for reply.

Screenshot of settings and page edit page.
![tailor-settings](https://user-images.githubusercontent.com/2470646/27021420-c75dc522-4f65-11e7-95b8-18ed4f3401d8.png)
![tailor-page](https://user-images.githubusercontent.com/2470646/27021440-f33c8070-4f65-11e7-80bf-5a9ace3e1fb1.png)

**Comment by andrew-worsfold** [comment]
You have _restricted_ all roles.   Restricting a role type prevents that role from using Tailor.

**Comment by PrafullaKumarSahu** [comment]
oh! That is my foolishness :D but in sandbox all roles are unrestricted and I can not drag and drop elements ??

**Comment by PrafullaKumarSahu** [comment]
In localhost also I tried dragging widgets and it does nothing ! Am I committing some similar mistake again ?

**Comment by andrew-worsfold** [comment]
Which browser are you using?  Are both instances showing errors in the console?

**Comment by PrafullaKumarSahu** [comment]
I am using google chrome, no, the localhost instance is not showing any error in console.

**Comment by PrafullaKumarSahu** [comment]
After repeated reload in localhost instance finally it is working may be few things are working, but I think I should spend sometime time to get it done, no idea why not working for sandbox . thank you for your kind help :+1:
