### ISSUE TITLE
Can not see custom element in Elements Panel

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [andrew-worsfold/tailor#123]
I am following this [documentation](https://support.gettailor.com/hc/en-us/articles/222095487-Registering-a-new-element) and able to create a custom panel, can add section and controls to it, but when I am trying to add and element to either elements panel or to the custom panel,I can not get it working, may be I am missing or documentation is unclear to me some how, need your help .

**Comment by andrew-worsfold** [comment]
The Tailor [sample theme](https://github.com/andrew-worsfold/tailor-sample-theme) has code for adding a custom panel.  Please give that a try and if you still have problems raise an issue in that repository.
