### ISSUE TITLE
Make element highlight and border clearer when editing

### ISSUE THREAD

**Issue by BinaryMoon** [andrew-worsfold/tailor#13]
The element highlight when hovering over an item is low contrast - so it's hard to tell what will be selected. This is even worse when the theme has a grey background (see image below).

![screen shot 2016-07-29 at 16 21 59](https://cloud.githubusercontent.com/assets/1004130/17253409/9820b132-55a8-11e6-8c31-0bac2f1d4d37.png)

I know it's not so attractive but I'd suggest using something with a lot more contrast especially on the hover. This this will improve accessibility as well. I'd probably go for a middle grey since it will work on both light and dark backgrounds.

**Comment by andrew-worsfold** [comment]
Good suggestion.  A majority of the themes I test on are light coloured, so I never encountered the type of contrast issue evident in your screenshot above.  I will update the colour to a darker grey as you suggest in 1.4.0.

**Comment by andrew-worsfold** [comment]
This is now available within the latest stable version of Tailor.  Please let me know if you have any other recommended changes.
