### ISSUE TITLE
Spinner styles breaks jetpack infinite load spinner styles

### ISSUE THREAD

**Issue by BinaryMoon** [andrew-worsfold/tailor#17]
There's a .spinner class being used in a few locations throughout the plugin - however this is clashing with Jetpacks infinite scroll spinner and making it disappear.

Would be nice if you could add a prefix to the spinner so that it doesn't affect things on the front end of the site.

**Comment by andrew-worsfold** [comment]
Good call.  This will be fixed in the next version.

**Comment by andrew-worsfold** [comment]
This should be addressed in the latest version (1.5.0).  Are you able to confirm that the issue has been resolved?

**Comment by BinaryMoon** [comment]
confirmed - all working well :)

**Comment by andrew-worsfold** [comment]
Great. Thanks for confirming!
