### ISSUE TITLE
scripts and styles are enqueued when not needed

### ISSUE THREAD

**Issue by BinaryMoon** [andrew-worsfold/tailor#18]
The scripts and styles are enqueued on every page, regardless of whether the page supports tailor (home page, and archives), or whether the user can make use of tailor. By that I mean that admin styles are enqueued for public visitors.

**Comment by andrew-worsfold** [comment]
Replicated and fixed.  This will be addressed in the next version.

**Comment by andrew-worsfold** [comment]
This should be addressed in the latest version (1.5.0).  Are you able to confirm that the issue has been resolved?

**Comment by BinaryMoon** [comment]
confirmed. All working well :)

**Comment by BinaryMoon** [comment]
sorry - not confirmed - I thought this was the spinner one.

On the homepage and category pages I am seeing the 'tailor-styles-css' stylesheet still included, along with the following js:
* /assets/js/dist/frontend.min.js
* /assets/js/dist/vendor/slick.min.js
* /assets/js/dist/vendor/modernizr.min.js
* /assets/js/dist/vendor/shuffle.min.js
* /assets/js/dist/vendor/magnific-popup.min.js

**Comment by andrew-worsfold** [comment]
I've added an additional check (is_singular()) to ensure scripts are not loaded for archive pages.  Is that working for you too?

**Comment by BinaryMoon** [comment]
Do you mean the check in includes/helpers/helpers-settings.php?

At the moment that check is saying:

`		if ( ! is_singular() || tailor()->is_canvas() || tailor()->is_template_preview() ) {
			return true;
		}`

But that says - if not a single page then include scripts doesn't it?

If you change it to:

`		if ( ! is_singular() ) {
			return false;
		}

		if ( tailor()->is_canvas() || tailor()->is_template_preview() ) {
			return true;
		}`

Then it works - at least on my local install.

**Comment by andrew-worsfold** [comment]
True - that's what happens when I try to do things late at night! :)

I've verified that this works as expected and included it in the latest version.

Thanks again!
