### ISSUE TITLE
imagesloaded.js is included in wordpress

### ISSUE THREAD

**Issue by BinaryMoon** [andrew-worsfold/tailor#19]
I noticed tailor has bundled it's own version of imagesloaded.

It's best practice to make use of scripts in WordPress so that the same scripts don't get loaded multiple times.

The WordPress script is registered with the handle imagesloaded.

**Comment by andrew-worsfold** [comment]
I agree.  This has been on my list of things to do for a while.  I'll switch over to the bundled version and, assuming there are no problems, have this included in the next release.

**Comment by andrew-worsfold** [comment]
I haven't included this in version 1.5.0, as although it worked in my local environment I encountered an error with the bundled WordPress imagesLoaded script not enqueuing in a staging environment.  I'm not sure, but on that server it looked like the script was bundled with masonry.js (which I'm not using).

Can imagesloaded definitely be enqueued using its own handle in the latest version of WordPress?

**Comment by BinaryMoon** [comment]
imagesloaded is a masonry dependency. I think in WordPress 4.5 they were in the same file, but in 4.6 they were separated, so if masonry is used then imagesloaded will also be enqueued.

You can see where they discuss this change here: https://core.trac.wordpress.org/ticket/32802#comment:20

**Comment by andrew-worsfold** [comment]
As previous prior to 4.6 need to be supported, I've kept a local copy of imagesloaded around just in case.  The bundled version will be used when available, but as I am not using the masonry.js script, it would be overkill to load it just for the benefit of using the bundled imagesloaded script.

Does that sound like a reasonable solution?

**Comment by BinaryMoon** [comment]
sounds good! :)

**Comment by andrew-worsfold** [comment]
Great!  That solution is in place now with Tailor 1.5.1.  I'll close out this issue :)
