### ISSUE TITLE
Defining tailor_custom_element as "wrapper" is undocumented or does not work?

### ISSUE THREAD

**Issue by olect-craftww** [andrew-worsfold/tailor#20]
Hi again,

$this->add_element( 'tailor_custom_section', array(
                'label'             =>  __( 'Custom section', 'tailor' ),
                'description'       =>  __( 'Custom image section.', 'tailor' ),
                'type'              =>  'wrapper',
            ) );

The above code, were type is set as 'wrapper' does not seem to work. Is there anything else I need to do to make my element work as a wrapper/container?

I need it to work when I drag a new Custom section element on to the canvas, it will create a section and fill it with my own content.

**Comment by andrew-worsfold** [comment]
If you're wrapper has anything other than simple markup, you may want to create a custom view to capture the "child container" (i.e., where the children should reside).  Admittedly, this is something that I haven't clearly documented yet, however I hope to update the documentation in the next few days.

When you say it doesn't work, what exactly do you mean?

**Comment by olect-craftww** [comment]
What I mean by doesn't work is; that like defined above, I set 'type' => 'wrapper' as you do in tailor-elements.php when elements are added. Based on the lack of documentation and me guessing how your code works, this seems more complex then it need/should be. Giving the possibility to define custom elements, setting type should alter how the elements interact together in placement/editing view.

**Comment by andrew-worsfold** [comment]
I've created a sample extension (i.e., plugin) and theme that demonstrate how one can add custom elements (including wrappers) and make other changes through the use of Tailor's APIs, actions and filters:

https://github.com/andrew-worsfold/tailor-sample-extension
https://github.com/andrew-worsfold/tailor-sample-theme

I'll continue to improve the documentation over time and welcome feedback of the sort you've provided.  If you continue to have issues creating or modifying elements (or other Tailor functionality for that matter), please don't heistate to raise another issue.

Cheers,
Andrew.
