### ISSUE TITLE
Double definition in tailor.pot

### ISSUE THREAD

**Issue by ManUtopiK** [andrew-worsfold/tailor#22]
I started translate tailor.pot file but there is an error:
```
tailor.pot:31: first occurence  
tailor.pot:1823: second occurence
```
I removed the second to continue translate but you should fix it.

**Comment by andrew-worsfold** [comment]
Looking at those lines in the tailor.pot file of the latest version of the plugin (1.5.0), they appear to be completed different.  To confirm, what specifically to those lines refer to?

Happy to try and consolidate the strings if possible, however the .pot file is generated automatically by a script and not something I have direct control over.

**Comment by andrew-worsfold** [comment]
The latest version of Tailor contains the changes from your pull request.  Is there anything else you think needs to be addressed under this issue?

**Comment by ManUtopiK** [comment]
Yes! It's fixed. Thx.
