### ISSUE TITLE
More prominent "Tailor this Page" button

### ISSUE THREAD

**Issue by ehrig** [andrew-worsfold/tailor#23]
When first using Tailor, it took me a little bit to find the "Tailor this Page" button, as I was expecting a page builder button right above the text editor. Having to scan the admin bar when editing a page, isn't very intuitive. A "Tailor this Page" button next to the "Add Media" button would help to become familiar with Tailor faster.

**Comment by andrew-worsfold** [comment]
Thanks for the feedback.  The decision to have it in the Admin Bar was driven mostly by the fact that the Edit Page link is located there.  I take your point, though, and will investigate ways of having this moved to (or another button/link) added above the editor.

If you have have code that does what you've suggested, feel free to create a pull request and I'll review it!

Cheers,
Andrew.
