### ISSUE TITLE
Compile SCSS

### ISSUE THREAD

**Issue by vincentducorps** [andrew-worsfold/tailor#29]
Hey Andrew,

What do you use to compile your SCSS ?

Thanks

**Comment by andrew-worsfold** [comment]
Hi Vincent, 

I use PHPStorm as an IDE, which has "file watchers" for SCSS among other things.  I have two of those set up to convert SCSS into CSS (and minified CSS) when file changes occur.  The JavaScript files I compile using Browserify in the terminal.

Did you encounter a problem with them, or are you just curious? 

Cheers,
Andrew.

**Comment by vincentducorps** [comment]
Just curious :)

I would like to make some UX improvements...

Thank you for the answer.

**Comment by andrew-worsfold** [comment]
Ok, great!  Let me know if you have any questions when doing so 😄
