### ISSUE TITLE
Add on panel

### ISSUE THREAD

**Issue by Wemago** [andrew-worsfold/tailor#3]
Why not build into Tailor an area where we could activate/deactivate add ons, being it more modular?

**Comment by andrew-worsfold** [comment]
For significant add-ons, the best approach would be to create an extension (like the new [Portfolio extension](https://github.com/andrew-worsfold/tailor-portfolio), or the upcoming WooCommerce extension).  For smaller addons or features within Tailor, there are plans to utilise the Settings page in the administrator backend to allow users to activate and deactivate features.

What sort of things did you have in mind in terms of "add ons"?  Do you envision the panel being in the frontend (i.e., builder interface) or in the backend (e.g., Tailor Settings page)?

**Comment by Wemago** [comment]
Sorry for the late answer. Would be both for frontend and backend. The idea would be to activate/deactivate based on client, so we would split tailor into modules, like you did with portfolio.

**Comment by andrew-worsfold** [comment]
What sorts of modules did you have in mind?  Are you mostly thinking about a way to enable/disable elements?

A few thoughts from my side:

1) It's possible for theme and plugin developers to use the built-in filters and hooks to change out-of-the-box functionality and admin options are available for the enabling/disabling of non-essential functionality like the JS and CSS editors.  That said, additional admin options _will_ be added for out-of-box elements.

2) Plugins and themes that add, remove or modify functionality can be activated or deactivated at any time.  Activating a plugin therefore would serve to 'activate' a Tailor module, depending on your definition of module.

3) Tailor has been designed to provide only elements and features that are useful to the majority of end users.  It's for this reason that portfolio and e-commerce features are provided in separate plugins, as not everyone will need or want them.

In the majority of cases, end users and theme developers could select (or recommend) only those extensions that are appropriate.  If, for example, a theme developer didn't want a particular element to be available when using their theme, they could easily disable it using the 'tailor_register_elements' hook; the same is true for plugin developers (though I wouldn't necessarily recommend that a plugin disable core elements without making it clear that it is doing so).

Another option could be for theme or plugin developer to add a new panel to Tailor (or section to the existing Settings panel) in which these types of options could be displayed.  Depending on what exactly you envision, there are quite a few ways of going about it..

I'm definitely open guess my concern is that given Tailor is, when installed by itself,

**Comment by andrew-worsfold** [comment]
As per the comment above, it's possible through the use of filters, actions and the built in API functions to add, change and remove most features in Tailor.  Elements can also be set up to check for dependencies (see active_callback).

For significant additions, an extension plugin should be considered.

If someone would like to elaborate on what 'modules' within Tailor could look like and what value they would offer over and above the items mentioned, please raise an issue and I will be happy to consider it.
