### ISSUE TITLE
Frontend component's initialisation not clean for ajax website

### ISSUE THREAD

**Issue by ManUtopiK** [andrew-worsfold/tailor#31]
With a single page application, a full ajax website or just new content added by ajax, all component's initialisation need to be reloaded for this new content. I did this by copy-paste in my theme the lines 21-81 of [this file](https://github.com/andrew-worsfold/tailor/blob/master/assets/js/src/frontend/frontend.js).

But this isn't DRY and not safe for future update. It will be better to wrap this component's initialisation in a function which could be call anywhere in our themes.

**Comment by andrew-worsfold** [comment]
Fair point.  SPA/AJAX sites weren't the focus during development, but there's no reason not to support them.  Were you anticipating a separate function for each element type?

What is the best practice when it comes to functions of this type?  Presumably they shouldn't be global scope, but accessible through the Tailor object..

**Comment by ManUtopiK** [comment]
> Were you anticipating a separate function for each element type?
No. I took all functions for reload all elements.

Maybe it will be accessible through something like `Tailor.initialize()`. But there is no Tailor object in front...

**Comment by andrew-worsfold** [comment]
I've updated the frontend scripts so that there is now a Tailor object.  You can use the initElements function to initialize all default elements.  Check out the latest commit for Tailor 1.5.5.

Does that work for you?

**Comment by ManUtopiK** [comment]
Perfect! That works well.
Thanks a lot for your work!

**Comment by ManUtopiK** [comment]
No, sorry, I made a mistake.
Tailor is not available as a global scope, or I missing something...

**Comment by andrew-worsfold** [comment]
You're right.  A fix for this will be added in the next release of Tailor.

**Comment by ManUtopiK** [comment]
It's work well this time. I got it with `window.Tailor.initElements();`.
Thanks.
