### ISSUE TITLE
evaluate/help/reuse grapesjs

### ISSUE THREAD

**Issue by pierreozoux** [andrew-worsfold/tailor#32]
We need to let user be able to create nice website/pages, without technical knowledge. A lot of project are reinventing the wheel, and I really think we should mutualize effort around a nice library and reuse that library.

Please see this issue:
https://github.com/artf/grapesjs/issues/20

**Comment by andrew-worsfold** [comment]
Hi @pierreozoux -

First let me say that that is a very impressive project.

I've tried to make Tailor as simple as possible and, while no doubt many people would find the power of GrapeJS incredibly valuable, I think the target audiences are very different.

I like the idea of collaborating on something which can be reused in a variety of different projects, and in fact have something in the pipeline that this could be very useful for.   I'll review the project in more detail and look forward to collaborating though GitHub in the future.

Cheers,
Andrew.
