### ISSUE TITLE
Expose a filter for the Shakespeare quotes

### ISSUE THREAD

**Issue by fjarrett** [andrew-worsfold/tailor#33]
It would be great to have a filter exposed for these so they can be easily modified by themes and plugins.

The `tailor_do_shakespeare()` function is pluggable, but that's only useful for plugins that happen to be loaded before Tailor is, and won't work for themes at all.

As a general rule, I think the pluggable function pattern is really only useful (and stable) for parent/child themes. That is, until the day WordPress _finally_ introduces some kind of plugin dependency management. 😜

**Comment by andrew-worsfold** [comment]
Good suggestion.

A simple filter (`tailor_do_shakespeare`) is now applied to the quote returned from the `tailor_do_shakespeare` function (i.e., placeholder text for empty content elements).  Check out the latest project commit (Tailor 1.5.5). 

Does that do the trick?

**Comment by andrew-worsfold** [comment]
@fjarrett - 

The filter provided in version 1.5.5 works and hopefully allows you to achieve everything you were wanting to.  If you experience any problems with this, please reopen the issue.

**Comment by arashohadi** [comment]
@andrew-worsfold 
Hi Andrew,

I am trying to hook into this filter from my theme but I can't get it working.
This is what I am using as a test in my theme's ```functions.php```:

```
add_filter('tailor_do_shakespeare', 'filter_placeholder_content');
function filter_placeholder_content($content)
{
    var_dump($content);
    return $content;
}
```

But nothing is output, it seems the hook is not recognized from my theme.
_Am I doing something wrong?_

I have also tried the same as above with ```tailor_default_settings``` with the same results (nothing output).

**Comment by andrew-worsfold** [comment]
@arashohadi  - 

You can filter the output of the 'tailor_do_shakespeare' function, but that will only be applied if you haven't specified custom placeholder text on the Settings page.  Using that setting is the preferred approach if you simply want to change the default placeholder text.

Cheers,
Andrew.
