### ISSUE TITLE
The spinner image is fuzzy on HiDPI displays

### ISSUE THREAD

**Issue by fjarrett** [andrew-worsfold/tailor#34]
I think the `.tailor-preview__viewport` element should use the [`spinner-2x.gif` that is already in core](https://github.com/WordPress/WordPress/blob/master/wp-includes/images/spinner-2x.gif).

<img width="56" alt="screen shot 2016-09-11 at 12 25 25 am" src="https://cloud.githubusercontent.com/assets/522158/18415406/b4a4320e-77b6-11e6-9f77-2f4bfa579fa5.png">

**Comment by andrew-worsfold** [comment]
The version for HiDPI displays should now be used in all places throughout Tailor.  Check out the associated commit and let me know if it works for you too 😄

**Comment by andrew-worsfold** [comment]
@fjarrett -

The fix provided in version 1.5.5. resolves the fuzzy spinner issue throughout the plugin.  If you encounter this problem elsewhere in Tailor please feel free to reopen the issue.
