### ISSUE TITLE
Bundle additional open source icon packs

### ISSUE THREAD

**Issue by fjarrett** [andrew-worsfold/tailor#35]
I love the Dashicons picker in the Box element. Given the amount of open source icons out there nowadays, are there any plans to bundle more packs?

https://genericons.com/ (145)
https://icomoon.io/#preview-free (490)
http://fontawesome.io/icons/ (634)

**Comment by andrew-worsfold** [comment]
Thanks for the feedback, Frankie!

It's already possible to add custom icon kits (`.zip` files generated from https://icomoon.io/) and use them alongside the default Dashicons (see the Settings page in the Admin area).   Were you aware of that and, if not, would you still like to see additional icon kits added?

My main concern with adding icon kits above and beyond the standard one (which ships with WordPress) is the added weight; especially if a majority of users don't end up using them.

**Comment by andrew-worsfold** [comment]
Hi @fjarrett -

As I haven't heard back from you (and given that users can already add whatever icon sets they want through the Settings page), I will close this issue.  Please do open another issue though if you think there are compelling reasons to include one or more other free icon sets by default.

Cheers,
Andrew
