### ISSUE TITLE
Make templates post type not public

### ISSUE THREAD

**Issue by BinaryMoon** [andrew-worsfold/tailor#37]
Templates are currently listed as a public post type. This means that they are visible on the front end of the site and could show up in  automatic sitemap plugins (and similar).

I would like to suggest that public be changed to false.
https://github.com/andrew-worsfold/tailor/blob/e6e041390db34c3167b404e6f737e2e0fed5dac5/includes/class-templates.php#L92

**Comment by andrew-worsfold** [comment]
Thanks!  This change will be included in the next release of the plugin.

**Comment by andrew-worsfold** [comment]
This change is now available here on GitHub and in version 1.5.6 in the WordPress repository.   As it's a simple change it should be good to close, but I'll let you confirm just to be sure 😄

**Comment by BinaryMoon** [comment]
looks good to me
