### ISSUE TITLE
Check if post is tailored

### ISSUE THREAD

**Issue by ManUtopiK** [andrew-worsfold/tailor#43]
There is a function `Tailor()->is_canvas()` to see if we are on the Tailor canvas (currently editing the page).
There is another function called `Tailor()->is_tailoring()` but **this is not** to check if current post was edited with Tailor. I don't understand the purpose of this public function...

It will be nice if we could check in the WP loop if the post was tailored, with a public function like `Tailor->is_tailored()`. Actually I do that with:
```php
if ( false == get_post_meta( $post->ID, '_tailor_layout', true ) ) {
   // $post not tailored
} else {
    // Tailored $post !
}
```

**Comment by andrew-worsfold** [comment]
@ManUtopiK -

Tailor comprises two parts: the "sidebar" and "canvas" (or preview window), presented in an iframe.  The `is_tailoring()` method is simply used to determine whether one is in the "sidebar" portion of the app (as there are styles and scripts unique to the sidebar).

I'm happy to add a check like the one that you proposed, but would like to understand more about the potential use cases for such a check.  Do you have an example of when/how you'd use it?

Cheers,
Andrew.

**Comment by ManUtopiK** [comment]
I use it to display information on front-end for logged-in user that got permissions to edit posts. Also, the edit post link in front-end is replaced by a tailor link when the post has been tailored, useful to prevent client mistake about #41.
And I use it to add a class in the article body...
But I think other use-cases can be found!

**Comment by andrew-worsfold** [comment]
Agreed, I like that idea.

The simple function below returns true if a given post has a Tailor layout.

`public function is_tailored( $post_id = null ) {
  $post = get_post( $post_id );
  return $post && false != get_post_meta( $post->ID, '_tailor_layout', true );
}`

I have this as a method in the Tailor class, so to access it will be identical to your original example:

`tailor()->is_tailored()`

How does that look?

**Comment by ManUtopiK** [comment]
That's look perfect! You're awesome :)
