### ISSUE TITLE
Option to delete Tailor layout for a given post

### ISSUE THREAD

**Issue by ManUtopiK** [andrew-worsfold/tailor#44]
:dart: 
No, I just want to know how to properly kill a tailored post : remove all stuff relative to Tailor but keep the content of the post. I didn't found a function to do that in Tailor class.

Possibility to kill a tailored post could be proposed in the admin notice. Relative to my comment here #41.

**Comment by andrew-worsfold** [comment]
@ManUtopiK -

So you'd like to keep the output of the Tailor builder, but remove the actual layout information (stored as post meta)?

As Tailor supports post revisions, restoring to an earlier revision (prior to Tailoring a page) will restore the post content as expected and also remove the layout information.  You could of course always revert to the "Tailor" revision and regain both the Tailored content and layout information.  I recognise that this is probably a little different to what you're asking for.

**Comment by andrew-worsfold** [comment]
@ManUtopiK -

This is included in the latest version of Tailor (on GitHub).  Can you please confirm if this works in accordance with your expectations?

**Comment by andrew-worsfold** [comment]
@ManUtopiK -

As this functionality is now present in the core plugin, I will close this issue.  Please don't hesitate to reopen it if it's not working correctly for you.
