### ISSUE TITLE
IE9 support

### ISSUE THREAD

**Issue by brettsmason** [andrew-worsfold/tailor#46]
Hi Andrew

[Following our discussion](https://support.gettailor.com/hc/en-us/community/posts/219069628-Front-end-styles-browser-support) I have been through and tested elements in IE9 and identified any styles that need to be added to add compatibility.

To sum it up the Scss to get this working is:

```
.tailor-ui {
    .tailor-column,
    .tailor-grid__item {
        float: left;
    }

    .tailor-section:before,
    .tailor-section:after,
    .tailor-grid:before,
    .tailor-grid:after {
        content: " ";
        display: table;
    }

    .tailor-section:after,
    .tailor-grid:after {
        clear: both;
    }
}
```

As you can see the only thing needed is to float columns and add a clearfix. Everything else I've tried so far works without a hitch. Great work on the CSS!

**Comment by andrew-worsfold** [comment]
Thanks for this, Brett!  Really appreciate your effort!

I will gain access to a machine with IE9 (I'm a Mac user) and/or spin up a VM to test this.  Just out of interest, how were you including this in your project?  Did you use a separate IE stylesheet (using conditional tags)?

**Comment by brettsmason** [comment]
Yep exactly that, just added conditional tags to load it if it's ie9 or less using the WordPress wp_style_add_data function. 

The only thing I haven't checked yet is there's a vertical alignment option on some elements and didn't check if that's related to flexbox or table cell.  If the later all should be good. 

Thanks for considering this!

**Comment by andrew-worsfold** [comment]
This has been included in the latest version of Tailor.

As I don't have an actual Windows machine to test on, would you be able to confirm whether you're getting the same results using the new version?

Regarding vertical alignment: that is achieved using flexbox too.  A separate update can be applied for those changes 😄

**Comment by andrew-worsfold** [comment]
@brettsmason -

I'll close this issue, but aim to improve IE9 support in upcoming releases.  If you identify any other specific issues with IE9 (or IE in general), please raise another issue.

Cheers,
Andrew.

**Comment by cloudratha** [comment]
Id prefer a better fix for this.
IE10 also requires the styles,as it doesn't support flex.
However IE10 doesn't support conditional tags either.

Perhaps check this alternative usage, using media queries.
[Media Queries and IE](http://keithclark.co.uk/articles/moving-ie-specific-css-into-media-blocks/media-tests/)

I'll do some tests and see if it works. Then we can just add the styles to the main css file.
