### ISSUE TITLE
Use existing wordpress widgets directly, rather than via widget areas.

### ISSUE THREAD

**Issue by micahscopes** [andrew-worsfold/tailor#53]
In Beaver Builder, you can use third-party and built-in widgets directly as page elements.  It'd be great if you could do this in Tailor too!

Would it be difficult to develop an extension that enables this?

Very nice plugin, by the way.  Thanks a lot :+1:

**Comment by andrew-worsfold** [comment]
Hi @micahscopes -

This is actually possible now in the latest version of the plugin (1.6.0) 😉 

Be sure to let me know if you encounter any issues (as this is brand new functionality) or have any suggestions or ideas related to it!

Cheers,
Andrew.

**Comment by andrew-worsfold** [comment]
PS - here's the blog post about it:

https://medium.com/@tailorwp/widgets-widgets-and-more-widgets-4722abeccf45#.1p2a5yiun

**Comment by micahscopes** [comment]
Oh wow... very cool!  didn't realize it was in settings!

This is truly a lovely plugin.

**Comment by andrew-worsfold** [comment]
Glad you like it!

It'll only get better through feedback from people like you so thanks for getting in touch.  Please do leave a review on the WordPress plugin page too if you have time, as that helps spread the word!
