### ISSUE TITLE
Allows us to add custom controls to built-in elements

### ISSUE THREAD

**Issue by reefki** [andrew-worsfold/tailor#55]
I have few elements that should be displayed fullwidth, such as image slider and Instagram gallery but I had problems with the section that doesn't allows them to be displayed correctly because they are wrapped by `tailor-section__content` div.

I think it would be nice if I can add some custom section settings e.g a checkbox to enable/disable full width section content etc, I think it could be done by placing following code at the end of `register_controls()` method of `Tailor_Section_Element` class:

`do_action('tailor_ELEMENTNAME_register_controls', $this);`.

This is also should be applied to all built-in elements.

**Comment by andrew-worsfold** [comment]
This is already possible.

`function tailor_modify_element( $element ) {

	// Do something with an existing setting (or control, or section etc.)
	$setting = $element->get_setting( 'setting-1' );
	
	// Or create new ones..
	$setting->add_setting( 'setting-2', array(
		'sanitize_callback'     =>  'tailor_sanitize_text',
	) );

	$setting->add_control( 'setting-2', array(
		'label'                 =>  __( 'An arbitrary control' ),
		'type'                  =>  'text',
		'priority'              =>  10,
		'section'               =>  'general',
	) );
}

add_action( 'tailor_element_register_controls_{$tag}', 'tailor_modify_element' );`

Please refer to the sample extension (or theme) for some high level examples of this, check out the documentation or simply look through the code.  If you find areas of documentation that you would like additional information, please let me know.

The upcoming Advanced Features extension will make extensive use of Tailor's API, hooks and filters.
