### ISSUE TITLE
Make all elements dynamic

### ISSUE THREAD

**Issue by reefki** [andrew-worsfold/tailor#56]
Please make all elements dynamic, at least enable dynamic by default so that we dont need to define it when registering an element.

Why? when a non-dynamic element's structure changed even if it just a class name that would be a nightmare. We have to look trough dozens, hundreds or probably thousands of posts and pages to find and replace the element to apply the structure changes.

**Comment by andrew-worsfold** [comment]
This is a trade off.

You can do this already using the `tailor_save_content_as_html` filter (return false).  This will not be the default in the core plugin, as the feedback has made it clear that usable content is more important than that which updates automatically.

Improvements to the saving of element data are underway and if it's possible in the future to have actual content that behaves dynamically, it will be included in the plugin.

Cheers,
Andrew.
