### ISSUE TITLE
Undefined index "id" and "class" on Form element

### ISSUE THREAD

**Issue by reefki** [andrew-worsfold/tailor#57]
Got this notices when WP debug enabled.

![screen shot 2016-10-17 at 10 44 03 am](https://cloud.githubusercontent.com/assets/10998084/19424830/e0c96e0a-9456-11e6-808c-05fac2b9df5e.png)

**Comment by andrew-worsfold** [comment]
Thanks for raising this, @reefki.

This is fixed in the upcoming version of Tailor.  1.6.8 introduces a range of improvements to the rendering functions, some of which were started in the current version (and result in these notices).

Cheers,
Andrew.

**Comment by andrew-worsfold** [comment]
Hi @reefki - 

Are you still seeing these notices?

**Comment by reefki** [comment]
@andrew-worsfold They are gone now! 

Thanks
