### ISSUE TITLE
Ability to enable/disable immediate update element when settings changed?

### ISSUE THREAD

**Issue by reefki** [andrew-worsfold/tailor#58]
Currently when element settings are changed it will immediately update the element, is it possible to disable it on some elements or specified controls?

I have a function to resize image dynamically when specified image size is not already exists and I have a text field to define the post thumbnail with default `300x250`, the problem comes when I decided to change the image size, for example I want to change the image height to `200`. Before I finished to type, for example I only typed `300x2` or `300x20` the element immediately refreshed and new image sizes `300x2` or `300x20 created.

I think it would be great if there is ability to enable/disable immediate update, or set a delay between value changed and element update or maybe use `blur` event instead of `change`.

**Comment by andrew-worsfold** [comment]
You can, when setting up settings, specify that they should refresh using JavaScript:

`$section_element->add_setting( 'setting', array(
	'sanitize_callback'     =>  'tailor_sanitize_color',
	'refresh'               =>  array(
		'method'                =>  'js',
	),
) );`

You can then use the setting JS API to respond to those setting changes however you like:

`SettingAPI.onChange( 'element:setting', function( to, from, model ) {

		// Do something with the DOM (the function is scoped to the element view)
		this.el.classList.add( 'custom-background-color' );
		this.$el.css( { 'background-color' : to } );

		// Or return a collection of custom CSS rules to apply
		return [ {
			selectors: [ '', '.selector-within-element' ],
			declarations: {
				'background-color' : to
			}
		} ];
	} );`

Would that work for your purposes?

**Comment by reefki** [comment]
Nice! But how to trigger update element from JS API?

**Comment by andrew-worsfold** [comment]
There's a setting in there by default to update the post title.  Why not just hide it using the same mechanism instead of refreshing the entire preview pane?

**Comment by reefki** [comment]
If page title is enabled and available in DOM I could simply `$('.page-title').hide()`, but how if page title is disabled and not available in DOM then user want to enable it? FYI my page title is has a background image that taken from featured image.

**Comment by reefki** [comment]
Found the solution, always show the page title if `$_GET['canvas']` is defined. Then toggle the visibility when setting changed.

**Comment by andrew-worsfold** [comment]
Good idea!

As the original point of this issue has been addressed, I'll close it now.  Thanks again for the feedback and questions.

**Comment by reefki** [comment]
@andrew-worsfold I think I found a bug on settings panel, here is my custom settings:

```
$panel->add_setting('show_page_title', array(
    'sanitize_callback' => 'tailor_sanitize_number',
    'default'           => '1',
    'refresh'           => array('method' => 'js')
));

$panel->add_control('show_page_title', array(
    'section'  =>  'general',
    'label'    =>  esc_html__('Show page header?', 'textdomain'),
    'type'     =>  'switch',
    'priority' =>  5
));
```
I set default value to `1` because all pages should have page title displayed by default. But with the settings above whenever I switched it off and save the settings then reload the tailor editor it will goes back to `1`.
