### ISSUE TITLE
Text not immediately visible after refreshing in Tailor Editor

### ISSUE THREAD

**Issue by salmankaleem5** [andrew-worsfold/tailor#6]
After clicking "Tailor this page" and then refreshing the page when in the Taylor editor, text descriptions of elements (in the left sidebar) are not immediately visible. However when I clicked edit on a content element, the text descriptions appeared again. When I clicked edit on a box element, the element descriptions didn't appear. 

I can reproduce the bug by doing the following:
* Click "Tailor this page"
* Refresh. Element text descriptions not visible
* Click edit on content box, text now visible. 
* Refresh
* Click edit on box element, text not visible

**Comment by andrew-worsfold** [comment]
I'm having trouble reproducing that issue.  Which browser/OS are you using?

**Comment by salmankaleem5** [comment]
Chrome Version 51, sorry should have specified that

**Comment by andrew-worsfold** [comment]
Thanks, I'm using Chrome too which makes things interesting.  OSX? Windows? Any chance I could get a screenshot of what you're seeing?  Thanks again!

**Comment by andrew-worsfold** [comment]
I've not heard anything back about this.  Version 1.3.0 moves to system fonts (in anticipation of this change in WordPress itself) so I will close this issue out.  Please test using the latest version and if the problem persists raise a new issue.
