### ISSUE TITLE
Parallax effect options [enhancement]

### ISSUE THREAD

**Issue by pedro-mendonca** [andrew-worsfold/tailor#60]
Hi @andrew-worsfold 

Congratulations for this great page builder.
I just tried to use the parallax effect on a section, but there is an issue that might prevent me to use it. It's speed, it seems that the background now is scrolling faster than the actual page scroll. To obtain a background moving effect, it's better to have it scrolling slower than the page itself.

Would be nice to have a setting, a textinput with a speed number, or a slider where you can control it's speed:

![screenshot 2016-10-20 09 20 16](https://cloud.githubusercontent.com/assets/7371591/19552938/fe2b4c84-96a9-11e6-8cfc-003910658d88.png)
- -1 - Slower than page
- 0 - No Parallax
- +1 - Faster than page

Currently it looks like the setting is Faster than page, It would be nice to also have the possibility to slide it somewhere -1 and 0, being 0 as parallax disabled.

Regards

**Comment by andrew-worsfold** [comment]
Thanks for the suggestion, @pedro-mendonca.

If I understand you correctly though, I am seeing the opposite.  Any chance you could provide a screencast (or similar) so that I can see what you're seeing?

Cheers,
Andrew.

**Comment by pedro-mendonca** [comment]
Hi,
Yes of course, live or should I make a gif of it?

**Comment by reefki** [comment]
I think you can use CSS transition to make it smoother:

```
.tailor-section__background {
    transition: transform 0.1s ease;
}
```

**Comment by pedro-mendonca** [comment]
Here is what I see, the background is faster than the page. This isn't an _ease_ issue, as it only eases it, but won't reverse it's direction.
Only have Tailor plugin active and [Tailor Sample Theme](https://github.com/andrew-worsfold/tailor-sample-theme)

![upwg5pu6j1](https://cloud.githubusercontent.com/assets/7371591/19561378/653a1eb6-96d0-11e6-8796-c520f01495b7.gif)

**Comment by andrew-worsfold** [comment]
@pedro-mendonca -

Apologies for the delay in getting around to this.  I've committed a change to address what you're seeing.  Could you please let me know if everything's looking and behaving as expected now?

Cheers,
Andrew.

**Comment by andrew-worsfold** [comment]
@pedro-mendonca  -

This is, based on my testing, now working properly (and in accordance with your description above).  As I've not heard anything from you I will close the issue, however please don't hesitate to reopen it if you believe more changes are required.

Cheers,
Andrew.

**Comment by pedro-mendonca** [comment]
Hi @andrew-worsfold 
Sorry for the long wait. Yes, it's working great now, the movement now looks like a distant background as supposed.
Nice job! Thanks :)
👍

**Comment by andrew-worsfold** [comment]
Great!  Thanks for confirming, @pedro-mendonca! 😄
