### ISSUE TITLE
Background video bug?

### ISSUE THREAD

**Issue by reefki** [andrew-worsfold/tailor#61]
I noticed there is an option to set a video background for section element, however the video doesn't show up.

I checked `shortcode-section.php` but there are seems to be none related to displaying video background. Do I need to insert the video manually by customizing the section html output?

**Comment by andrew-worsfold** [comment]
This is an upcoming feature in the free advanced features extension, so no it's not a bug 😄 

Good spotting though!

**Comment by reefki** [comment]
Thanks! 😄
