### ISSUE TITLE
Can't use "vh" as unit for section minimum height anymore

### ISSUE THREAD

**Issue by Arood** [andrew-worsfold/tailor#65]
After updating to 1.7.2, it seems like it's not possible to set 100vh as minimum height on a section to achieve full-height content anymore. Is this an intended change or a bug?

**Comment by andrew-worsfold** [comment]
The latest version validates both the numerical value of a setting and the unit provided (if any) for certain fields.  The whitelist doesn't currently include vh and vw units, but I will add these in the next release.

FYI - the "whitelist" currently comprises:

`[
	"px",
	"%",
	"in",
	"cm",
	"mm",
	"pt",
	"pc",
	"em",
	"rem",
	"ex"
]`

Defaulting to px if no unit is specified.

Let me know if there are any others that you'd like to see added.

**Comment by andrew-worsfold** [comment]
@Arood - Can you please confirm whether the latest commit (1.7.3) resolves this issue for you?

**Comment by Arood** [comment]
Seems to work now! Thanks!
