### ISSUE TITLE
Filter CSS rules built-in elements

### ISSUE THREAD

**Issue by reefki** [andrew-worsfold/tailor#66]
I've added few additional controls to section element, some of them are require CSS. There is filter to register element's controls, but it seems like there is no filter for CSS rules or am I missing something?

**Comment by andrew-worsfold** [comment]
You can use the `tailor_element_css_rule_sets` filter to add additional custom CSS rules for default elements (whether associated with default controls or custom ones that you've added).  For custom elements, custom CSS rules should be added using the `generate_css` method.

If you want to make use of live preview functionality (i.e., JavaScript applied changes) ensure you update the setting to reflect that and add the necessary callbacks using the Settings API.

**Comment by reefki** [comment]
@andrew-worsfold sorry to re-open this issue!

It looks like `tailor_element_css_rule_sets` filters are never triggered in the frontend. Trying to check with:

```
add_filter('tailor_element_css_rule_sets', function ($css_rule_sets, $atts, $element) {
    print_r($atts);
}, 1, 3);
```

They're only triggered in the canvas editor.

**Comment by reefki** [comment]
Ok, disregard my question above. The custom CSS is saved as a meta value so to trigger the filters I have to make changes to the element settings.
