### ISSUE TITLE
Section Maximum Width blank issues

### ISSUE THREAD

**Issue by daviedR** [andrew-worsfold/tailor#69]
Hi Andrew,

In Section's settings, if we tried to input a value (e.g. 800 or 800px) and the screen rendered the change, then delete them back to blank, The section's generated CSS has `max-width: 0px`.

Can you disable the generated CSS if the value is blank, so it would use default style.

**Comment by andrew-worsfold** [comment]
Good catch.  This is a bug and I have a fix which will be included in the next release 😄

**Comment by andrew-worsfold** [comment]
@daviedR -

A potential fix is included in the latest version (on GitHub).  Please let me know if this solves the issue for you.

**Comment by andrew-worsfold** [comment]
@daviedR -

As the fix referenced above resolves the issue based on my tests, I will close this issue.  Please don't hesitate to reopen it if you're still having problems.
