### ISSUE TITLE
Can't add <iframe> to a Content element

### ISSUE THREAD

**Issue by arashohadi** [andrew-worsfold/tailor#71]
I can't seem to add an <iframe> element with Tailor. It works using the regular Wordpress editor.

Example: 
```
<iframe width="1280" height="720" src="https://www.youtube.com/embed/tfMyLMuaXjI?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
```

**Comment by andrew-worsfold** [comment]
@arashohadi -

I've added support for iframes in the latest version (up on GitHub).  Can you please confirm if this works for you?

**Comment by arashohadi** [comment]
@andrew-worsfold Thank you, it works!
