### ISSUE TITLE
Can't save changes directly from text field in TinyMCE

### ISSUE THREAD

**Issue by arashohadi** [andrew-worsfold/tailor#72]
I can't save changes or text input directly from the Text tab in TinyMCE unless I 
- change to Visual and back to Text
_or_
- change to Visual and make a change there

See attached gif showing this

Happens on 1.7.4 and on the latest commit on the master branch

![text_tinymce_tailor](https://cloud.githubusercontent.com/assets/10348243/20239512/d7fe2b48-a901-11e6-8af4-daef9b05172a.gif)

**Comment by andrew-worsfold** [comment]
@arashohadi -

The latest commit should fix this issue.  Can you please confirm that this is working for you too?

**Comment by arashohadi** [comment]
@andrew-worsfold Yes, thank you, it works now!
