### ISSUE TITLE
Stop Tailor from moving default customizer settings

### ISSUE THREAD

**Issue by BinaryMoon** [andrew-worsfold/tailor#73]
It looks like Tailor is moving the header and background colour properties from the default WordPress customizer position into the Tailor menu.

I don't think this should be done for a number of reasons.

1. It means that the settings are not where users expect them (it took me about 10 minutes of searching to find it)
2. It breaks plugins that hook into the colours panel - including my own plugin, Styleguide - https://wordpress.org/plugins/styleguide/ - and I'm sure there are more
3. It's not actually a Tailor setting, it's a WordPress setting.

I can see the appeal of having the all of the colours kept together, but I don't think it's logical/ expected - but the biggest argument against is that it can break plugins.

**Comment by andrew-worsfold** [comment]
Good point.  I've updated the Customizer section IDs to be more specific (e.g., tailor_colors).  This will address the problem and will be included in the next release.

**Comment by andrew-worsfold** [comment]
@BinaryMoon -

This has been resolved in the latest commit.  I've created more specific panel and section names for the Tailor controls to avoid conflicts with themes and other plugins.  Could you please confirm that the controls are now displaying in the correct place in your theme?

Thanks for bringing this to my attention!

**Comment by BinaryMoon** [comment]
All fixed - thank you! :)
