### ISSUE TITLE
get_current_screen() error (with New User Approve Plugin)

### ISSUE THREAD

**Issue by apintocr** [andrew-worsfold/tailor#75]
I get the following error when I use this with [New User Approve Plugin](https://github.com/picklewagon/new-user-approve/)

```
PHP Fatal error:  Uncaught Error: Call to undefined function get_current_screen() in \plugins\new-user-approve\includes\user-list.php:204
Stack trace:
#0 \wp-includes\plugin.php(600): pw_new_user_approve_user_list->filter_by_status(Object(WP_User_Query))
#1 \wp-includes\class-wp-user-query.php(526): do_action_ref_array('pre_user_query', Array)
#2 \wp-includes\class-wp-user-query.php(82): WP_User_Query->prepare_query(Array)
#3 \wp-includes\user.php(556): WP_User_Query->__construct(Array)
#4 \plugins\tailor\includes\helpers\helpers-general.php(62): get_users()
#5 \plugins\tailor\includes\elements\class-user.php(51): tailor_get_users()
#6 \plugins\tailor\includes\elements\abstract-element.php(285): Tailor_User_Element->register_controls()
#7 \plugins\tailor\includes\elements\abstract-el in \plugins\new-user-approve\includes\user-list.php on line 204
```

Any Tips?
NOTE: Also posted on [New User Approve Git Issues](https://github.com/picklewagon/new-user-approve/issues/49).

**Comment by andrew-worsfold** [comment]
@apintocr -

This should now be resolved in the latest commit.  Could you please let me know if this is working for you?

Cheers,
Andrew.

**Comment by andrew-worsfold** [comment]
@apintocr -

I was able to reproduce the issue that you were experiencing and can also confirm that it is no longer happening using the latest version.  As I have not heard anything from you, I will close this issue.  Please don't hesitate to reopen it if you're still having issues.

Cheers,
Andrew.

**Comment by apintocr** [comment]
@andrew-worsfold I'm sorry for not replying before, had a rough week and no time to check this out.
I can confirm this is **working as expected**.

Thank you very much!

**Comment by andrew-worsfold** [comment]
Awesome.  Thanks for confirming, @apintocr!
