### ISSUE TITLE
Custom wrapper element placement

### ISSUE THREAD

**Issue by cloudratha** [andrew-worsfold/tailor#77]
I wanted to create my own section wrapper that has it's own rules and to not use the default child container. I basically copied the default Tailor Section element and shortcode and made the changes I needed.

My issue is that it cannot be placed next to a section wrapper, and only inside the section block.
Removing all the elements on a page, leaves a default section wrapper.

I'm trying to make a section that doesn't use the tailor-section__content class as a child container.
I just want to be able to use a combination of my custom section and the default.

Otherwise great plugin and best page builder I've used so far.

**Comment by andrew-worsfold** [comment]
Hi @cloudratha -

You can modify the Section model or view in the frontend (JavaScript) or simply change the defined child container using PHP when registering elements (use the provided hooks to change that attribute for the Section element).  The exact approach will depend on what you're looking to do, but you should be able to achieve pretty much anything.

Cheers,
Andrew.

**Comment by cloudratha** [comment]
I was looking to create a fullwidth section that wasn't constrained by the tailor-section__content. My work around was to modify the section to be fullwidth and then create my own content section. That worked pretty well.

**Comment by andrew-worsfold** [comment]
Ok, cool.  The rendered HTML and behaviour of all default elements can be modified so I will look to create some tangible examples for those who are interested in doing it in the future.

Incidentally, I have just committed (and uploaded to the WordPress Plugin Repository) new versions of Tailor and the Advanced Features extension.  The latest version of the Advanced Features extension offers the ability to stretch Section backgrounds and/or content to the full width of the screen, if that's something that interests you.

**Comment by cloudratha** [comment]
Will definitely take a look. Thanks for the heads up.
