### ISSUE TITLE
Tailor Sidebar.css overrides WordPress media library styles

### ISSUE THREAD

**Issue by conwaydev** [andrew-worsfold/tailor#98]
On line 30 of _panels.scss you have a CSS rule for `.search-form { padding: 0 12px; }` that is interfering with the WordPress media library search input.

Heres a couple screenshots detailing the bug using the Tailor advanced plugin:

![screen shot 2017-03-15 at 3 23 53 pm](https://cloud.githubusercontent.com/assets/1868805/23969604/063b85f2-0995-11e7-86cc-473ceb9c0722.png)

![screen shot 2017-03-15 at 3 23 56 pm](https://cloud.githubusercontent.com/assets/1868805/23969665/382f2d84-0995-11e7-87a3-d182003a626e.png)

![screen shot 2017-03-15 at 3 24 08 pm](https://cloud.githubusercontent.com/assets/1868805/23969672/3dae2472-0995-11e7-8de8-dbf209b001e7.png)

As you can see in the 3rd screenshot I have commented out the style rule inside the chrome developer tools and the search bar is visible again. I will say that if you tab inside the media library modal till you hit the search bar it focuses itself, but it seems like this is the root of the problem.

**Comment by andrew-worsfold** [comment]
Thanks for bringing this to my attention, @conwaydev.  I've created a fix that will be included in the next release.

**Comment by andrew-worsfold** [comment]
@conwaydev - The latest release should have resolved the issue (if I'm understanding it correctly).  Please let me know if it does.

Cheers,
Andrew.

**Comment by conwaydev** [comment]
Awesome!
